### ISSUE TITLE
Unsecure handling with decrypted vaults

### ISSUE THREAD

**Issue by offlinehoster** [adambullmer/sublime_ansible_vault#1]
When using decrypt the file is unencrypted written to the disk. If you now make a mistake and save the file by strg+s you will have a plaintext vault file with secrets on your disk.

That's a security bug i think.

The way should be to write this to a temp file or to the mem and edit the file there...and save it back as encrypted file.

**Comment by adambullmer** [comment]
This functionality is no different than how decrypting and re-encrypting a vault using the ansible CLI works today.
The `View` command will show a temporary in memory file of the contents, however it is not an editable file. (Also still needing to figure out how to set the syntax highlighting on it correctly).

**Comment by offlinehoster** [comment]
When you save a softlink file on a linux system you only change the destination inode not the softlink inode! 

That is a bug!
