### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by pujan14** [adambullmer/sublime_ansible_vault#10]
I get following error/warning when I try to use any of the functions in a dialogbox with ok button and none of the functions works. This happens when I try with a password file.
ansible 2.4.3 on Linux

"[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of become which is a 
generic framework . This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg."

When I try using the prompt for password I get following error.
"[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of become which is a 
generic framework . This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Vault password: 
"

**Comment by adambullmer** [comment]
Are you using Sublime 2 or 3?

**Comment by pujan14** [comment]
Sublime 3

**Comment by adambullmer** [comment]
A few more questions to help replicate this issue:
- What is your system version of ansible
- do you need elevated privileges (i.e. su) to use it
- which python version is ansible installed to (from the stack trace I'm guessing 2.7)
- was ansible `sudo pip` installed

It's possible this might accelerate the feature of being able to specify your ansible path

**Comment by pujan14** [comment]
Here are some details you want

from ansible --version
```
ansible 2.4.3.0
  config file = /home/ps/ansible.cfg
  configured module search path = [u'/home/ps/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]
```
I don't need elevated privileges to use ansible, I have been using this plugin since about a year without any issues but I think after update in sublime or ansible(more likely) things stopped working.
ansible is installed with pip as root. I have tried ansible 2.5 beta1 as well as ansible devel branch.

I don't know if it matters or not but I am using debian on testing branch with sublime beta versions so it could also be something specifically in my system.

By reading the code I could not locate where the error message is coming from so if you can't reproduce the issue some hints about how to debug on my system would be helpful.

**Comment by adambullmer** [comment]
I haven't tried to reproduce this one just yet, however I discovered that when using the direct password prompt, I would get a warning from getpass (present in part of your output) and the plugin was treating that as a hard error. 

I think #11 will have a side effect of fixing this issue, however does not address the specific deprecation warning. Since it is just a warning for now, I'll hide that from the output, but this is a future problem waiting to happen for sure.
