### ISSUE TITLE
Decrypt locks up Sublime Text 3 (3126) on Linux

### ISSUE THREAD

**Issue by jdoss** [adambullmer/sublime_ansible_vault#2]
When I try to decrypt an encrypted vault file the plugin prompts for a password and after inputting it manually Sublime Text locks up on Fedora 24 Linux. Also setting the `password` or `password_file` in the user settings or in the project file does not work. The plugin still prompts for a password.

**Comment by adambullmer** [comment]
I think this should be fixed in the release `1.1.0`. Can you confirm this is still a problem?

**Comment by jdoss** [comment]
LGTM. Thanks @adambullmer :+1:

**Comment by adambullmer** [comment]
Cool. Closing this one out them
