### ISSUE TITLE
Per-project settings

### ISSUE THREAD

**Issue by bretmartin** [adambullmer/sublime_ansible_vault#4]
https://github.com/adambullmer/sublime_ansible_vault/blob/master/AnsibleVault.sublime-settings#L13 indicates it's possible to specify settings for this package on a per-project basis. I'm having trouble figuring out how to do this -- putting `password_file` in my project settings, either at the top level or inside a new `settings` dict doesn't work.

Can you confirm this is supposed to work and help me understand how? (If it doesn't actually work, I'm happy to work on adding this support after learning the "right" Sublime Text way to do it.)

**Comment by adambullmer** [comment]
Sorry for the silence on this issue. I'm going to set aside some time to give this plugin some love this weekend.

**Comment by adambullmer** [comment]
Added per-project settings, See https://github.com/adambullmer/sublime_ansible_vault#project-specific-settings for format
